version: 2
jobs:
  test:
    docker: # use the docker executor type; machine and macos executors are also supported
      - image: python:3.7-alpine # the primary container, where the job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: python3 -m unittest tests/test_compiled_code.py
  deploy:
    docker: # use the docker executor type
      - image: docker:stable-git # the primary container, where the job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - setup_remote_docker:
          docker_layer_caching: true # Enables Docker Layer Caching here to speed up image building
      - run: apk add make # Add MAKE in order to get the version and the the corresponding tagging from the Makefile
      - run: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - run: sh 'scripts/docker_build.sh'
      - run: sh 'scripts/docker_check.sh'
      - run: sh 'scripts/docker_push.sh'
workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
